site:
  production_url: "https://arge.biges.com"
  title: "Biges Ar-Ge Merkezi"
  subtitle: "Yazılım Geliştirme Blogu"
  logo: "logo.png"
  cover_image: "cover.jpg"
  social:
    twitter: "BigesEng"
    github: "biges"
    vimeo: "biges"
    google_analytics: "UA-125596610-1"
    disqus: "bigesarge"
  main_author:
    name: "ARGE Ekibi"
    email: "arge@biges.com"
    link: "https://biges.com"
    bio: "Biges ARGE Ekibi"
    twitter: "BigesEng"
    github: "biges"
