source 'https://rubygems.org'
ruby '2.6.0'

gem 'middleman', '~> 4.3', '>= 4.3.3'
gem 'middleman-livereload', '~> 3.4', '>= 3.4.6'
gem 'middleman-deploy'
gem 'middleman-syntax'
gem 'middleman-blog'
gem 'builder', '~> 3.2', '>= 3.2.3'
gem 'stringex'
gem 'redcarpet'
gem 'sanitize'
