source 'http://rubygems.org'
ruby '2.2.2'
gem 'middleman', '~> 3.3.8'
gem 'middleman-livereload', '~> 3.1.0'
gem 'middleman-deploy'
gem 'middleman-syntax'
gem 'middleman-blog'
gem 'builder', '~> 3.0'
gem 'stringex'
gem 'redcarpet'
gem 'sanitize'
