source 'http://rubygems.org'

gem 'middleman'
gem 'middleman-livereload'
gem 'middleman-deploy', '~> 2.0.0.pre.alpha'
gem 'middleman-syntax'
gem 'middleman-blog', '~> 4.0'
gem 'builder'
gem 'stringex'
gem 'redcarpet'
gem 'sanitize'